### ISSUE TITLE
Нужно перестать использовать "Upload files".

### ISSUE THREAD

**Issue by NeverMine17** [IngenerkaTeamNewYork/general#1]
Использовать "Upload files" очень опасно, т.к можно переписать версию другого человека.

---

Так-же рекомендую всем отослать [эту](https://habrahabr.ru/post/272531/) ссылку.

**Comment by mabramovsd** [comment]
У репозиториев, начинающихся с приставки pre, одна ветка. И в каждый момент времени ровно один разработчик (сперва Вася, потом Петя, потом Саша, но никогда одновременно Вася, Петя и Саша). Соответственно, они ничего не перезапишут, т.к. работают друг за другом. Когда дойдем до редакторов, будут разные ветки, причем мастер будет закрыт от всех

Я согласен, upload files - зло. Но я не верю, что прямо сейчас можно заставить делать pull request, git clone, git push человека, который просит меня помочь, потому что забыл, как пишется цикл. Поэтому я выбрал вот такое, очень своеобразное понимание совместной разработки

P.S. Про ссылку - не обещаю, но про githowto и курс по git на hexlet точно упомяну. Правда, не в сентябре точно

**Comment by NeverMine17** [comment]
С вами согласен, но есть ещё один минус.
Так как Upload Files просто минусует скажем `a/main.cpp` и плюсует `b/main.cpp`, diff получается достаточно большой. А если ещё бинарные файлы аплодится типо bmp размером 2-3 мб то получается ещё хуже.

**Comment by NeverMine17** [comment]
@mabramovsd 
> Когда дойдем до редакторов

Какие редакторы?
> причем мастер будет закрыт от всех

Т.е `protected`?
